const KEY='mrp_stability_v2';
const seed=[['Alenochka_White','Администратор',0,0],['Sergei_Tuvinskiy','Администратор',2,0],['Lorenzo_Bananov','Стажер',1,0],['Tim_Morozov','Стажер',2,0],['Sanek_Morozov','Стажер',0,0],['Roman_Xametov','Стажер',0,0],['Rayan_Mira','Стажер',0,0],['Ramzan_Parker','Стажер',0,0]];
let db=load(),month=new Date(2026,9,1);
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.staff)return x}catch(e){}return{staff:seed.map((x,i)=>({id:'s'+i,name:x[0],role:x[1],yellow:x[2],red:x[3]})),marks:{}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
const pad=n=>String(n).padStart(2,'0'),dateKey=(y,m,d)=>y+'-'+pad(m+1)+'-'+pad(d),days=()=>new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),mark=(id,k)=>db.marks[id+'|'+k]||{status:'none',norm:0,note:''};
const months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
function stats(a){let done=0,inactive=0,total=0,norm=0;for(let d=1;d<=days();d++){let x=mark(a.id,dateKey(month.getFullYear(),month.getMonth(),d));if(x.status!=='none')total++;if(x.status==='norm')done++;if(x.status==='inactive')inactive++;norm+=Number(x.norm)||0}return{done,inactive,total,norm,pct:total?Math.round(done/total*100):0}}
function renderMonth(){monthLabel.textContent=months[month.getMonth()]+' '+month.getFullYear();let q=search.value.toLowerCase(),list=db.staff.filter(a=>a.name.toLowerCase().includes(q)&&(!role.value||a.role===role.value));let avg=list.length?Math.round(list.reduce((s,a)=>s+stats(a).pct,0)/list.length):0;statsEl.innerHTML=stat('Состав',list.length)+stat('Средняя стабильность',avg+'%')+stat('Жёлтые карточки',list.reduce((s,a)=>s+a.yellow,0))+stat('Красные карточки',list.reduce((s,a)=>s+a.red,0));cards.innerHTML=list.length?list.map(a=>{let st=stats(a),ds=Array.from({length:days()},(_,i)=>{let d=i+1,k=dateKey(month.getFullYear(),month.getMonth(),d),x=mark(a.id,k);return '<button class="day '+x.status+'" onclick="openMark(\''+a.id+'\',\''+k+'\')">'+d+'</button>'}).join('');return '<article class=card><div class=top><div><div class=name>'+esc(a.name)+'</div><div class=role>'+a.role+'</div></div><div class=warnings><span class=pill>🟨 '+a.yellow+'/3</span><span class=pill>🟥 '+a.red+'/1</span></div></div><div class=days>'+ds+'</div><div class=progress><div style="width:'+st.pct+'%"></div></div><div class=foot><span>Норма: '+st.norm+' · Неактив: '+st.inactive+'</span><b>'+st.pct+'%</b></div></article>'}).join(''):'<div class=empty>Ничего не найдено</div>'}
function stat(n,v){return '<div class=stat><span>'+n+'</span><b>'+v+'</b></div>'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderDay(){let k=dayDate.value;if(!k)return;dayList.innerHTML=db.staff.map(a=>{let x=mark(a.id,k),txt=x.status==='norm'?'Норма':x.status==='inactive'?'Неактив':'Нет данных';return '<div class=dayRow><div><b>'+esc(a.name)+'</b><div class=muted>'+a.role+(x.note?' · '+esc(x.note):'')+'</div></div><div class=dayMeta><span class="status '+x.status+'">'+txt+'</span><b>'+((x.norm||0))+'</b><button class=small onclick="openMark(\''+a.id+'\',\''+k+'\')">Изменить</button></div></div>'}).join('')}
function renderManage(){manageList.innerHTML=db.staff.map(a=>'<div class=manageRow><div><b>'+esc(a.name)+'</b><div class=muted>'+a.role+' · Ж/К '+a.yellow+'/3 · К/К '+a.red+'/1</div></div><button class=small onclick="openStaff(\''+a.id+'\')">Изменить</button></div>').join('')}
function renderAll(){renderMonth();renderDay();renderManage()}
window.openMark=(id,k)=>{let a=db.staff.find(x=>x.id===id),x=mark(id,k);editId.value=id;editDate.value=k;editStatus.value=x.status;editNorm.value=x.norm||'';editNote.value=x.note||'';editTitle.textContent=a.name;editDialog.showModal()}
editForm.onsubmit=e=>{e.preventDefault();let key=editId.value+'|'+editDate.value;if(editStatus.value==='none')delete db.marks[key];else db.marks[key]={status:editStatus.value,norm:Number(editNorm.value)||0,note:editNote.value.trim()};editDialog.close();save()}
window.openStaff=id=>{let a=db.staff.find(x=>x.id===id);staffId.value=id||'';staffName.value=a?a.name:'';staffRole.value=a?a.role:'Администратор';staffYellow.value=a?a.yellow:0;staffRed.value=a?a.red:0;staffTitle.textContent=a?'Изменить сотрудника':'Добавить сотрудника';deleteStaff.hidden=!a;staffDialog.showModal()}
addBtn.onclick=()=>openStaff();staffForm.onsubmit=e=>{e.preventDefault();let id=staffId.value,a=db.staff.find(x=>x.id===id),data={name:staffName.value.trim(),role:staffRole.value,yellow:Number(staffYellow.value)||0,red:Number(staffRed.value)||0};if(a)Object.assign(a,data);else db.staff.push({id:'s'+Date.now(),...data});staffDialog.close();save()}
deleteStaff.onclick=()=>{let id=staffId.value;if(confirm('Удалить сотрудника и все его отметки?')){db.staff=db.staff.filter(x=>x.id!==id);Object.keys(db.marks).filter(k=>k.startsWith(id+'|')).forEach(k=>delete db.marks[k]);staffDialog.close();save()}}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));['month','day','manage'].forEach(v=>document.querySelector('#'+v+'View').hidden=v!==b.dataset.view);renderAll()});
prev.onclick=()=>{month.setMonth(month.getMonth()-1);renderMonth()};next.onclick=()=>{month.setMonth(month.getMonth()+1);renderMonth()};search.oninput=role.onchange=renderMonth;theme.onclick=()=>document.body.classList.toggle('light');dayDate.value=new Date().toISOString().slice(0,10);dayDate.onchange=renderDay;
const statsEl=document.querySelector('#stats');renderAll();