document.addEventListener('DOMContentLoaded',async()=>{const $=id=>document.getElementById(id),sb=window.supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_KEY);let db={staff:[],marks:{}},month=new Date(),user=null;const months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],pad=n=>String(n).padStart(2,'0'),key=(y,m,d)=>y+'-'+pad(m+1)+'-'+pad(d),dim=()=>new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),mark=(id,k)=>db.marks[id+'|'+k]||{status:'none',norm:0,note:''};
async function session(){const {data}=await sb.auth.getSession();user=data.session?.user||null;$('authGate').hidden=!!user;$('app').hidden=!user;if(user)await load()}
async function load(){const [s,m]=await Promise.all([sb.from('staff').select('*').order('created_at'),sb.from('daily_marks').select('*')]);if(s.error||m.error){$('connection').textContent='Ошибка базы: '+(s.error?.message||m.error?.message);return}db.staff=s.data.map(x=>({id:x.id,name:x.name,role:x.role,yellow:x.yellow_cards,red:x.red_cards}));db.marks={};m.data.forEach(x=>db.marks[x.staff_id+'|'+x.mark_date]={status:x.status,norm:x.norm_value,note:x.note});$('connection').textContent='● Данные синхронизированы';renderAll()}
function metrics(a){let ok=0,bad=0,total=0,norm=0;for(let d=1;d<=dim();d++){const x=mark(a.id,key(month.getFullYear(),month.getMonth(),d));if(x.status!=='none')total++;if(x.status==='norm')ok++;if(x.status==='inactive')bad++;norm+=+x.norm||0}return{bad,norm,pct:total?Math.round(ok/total*100):0}}
function renderMonth(){$('monthLabel').textContent=months[month.getMonth()]+' '+month.getFullYear();const q=$('searchInput').value.toLowerCase(),rv=$('roleSelect').value,list=db.staff.filter(a=>a.name.toLowerCase().includes(q)&&(!rv||a.role===rv)),avg=list.length?Math.round(list.reduce((s,a)=>s+metrics(a).pct,0)/list.length):0;$('stats').innerHTML=[['Состав',list.length],['Средняя стабильность',avg+'%'],['Жёлтые карточки',list.reduce((s,a)=>s+a.yellow,0)],['Красные карточки',list.reduce((s,a)=>s+a.red,0)]].map(x=>'<div class="stat"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('');$('cards').innerHTML=list.map(a=>{const st=metrics(a),ds=Array.from({length:dim()},(_,i)=>{const d=i+1,k=key(month.getFullYear(),month.getMonth(),d),x=mark(a.id,k);return '<button class="day '+x.status+'" data-mark="'+a.id+'" data-date="'+k+'">'+d+'</button>'}).join('');return '<article class="card"><div class="top"><div><div class="name">'+esc(a.name)+'</div><div class="role">'+esc(a.role)+'</div></div><div class="warnings"><span class="pill">🟨 '+a.yellow+'/3</span><span class="pill">🟥 '+a.red+'/1</span></div></div><div class="days">'+ds+'</div><div class="progress"><div style="width:'+st.pct+'%"></div></div><div class="foot"><span>Норма: '+st.norm+' · Неактив: '+st.bad+'</span><b>'+st.pct+'%</b></div></article>'}).join('')||'<div class="empty">Состав пока пуст</div>';document.querySelectorAll('[data-mark]').forEach(b=>b.addEventListener('click',()=>openMark(b.dataset.mark,b.dataset.date)))}
function renderDay(){const k=$('dayDate').value;$('dayList').innerHTML=db.staff.map(a=>{const x=mark(a.id,k),txt=x.status==='norm'?'Норма':x.status==='inactive'?'Неактив':'Нет данных';return '<div class="dayRow"><div><b>'+esc(a.name)+'</b><div class="muted">'+esc(a.role)+(x.note?' · '+esc(x.note):'')+'</div></div><div class="dayMeta"><span class="status '+x.status+'">'+txt+'</span><b>'+x.norm+'</b><button class="small editDay" data-id="'+a.id+'">Изменить</button></div></div>'}).join('');document.querySelectorAll('.editDay').forEach(b=>b.onclick=()=>openMark(b.dataset.id,k))}
function renderManage(){$('manageList').innerHTML=db.staff.map(a=>'<div class="manageRow"><div><b>'+esc(a.name)+'</b><div class="muted">'+esc(a.role)+' · Ж/К '+a.yellow+'/3 · К/К '+a.red+'/1</div></div><button class="small editStaff" data-id="'+a.id+'">Изменить</button></div>').join('')||'<div class="empty">Добавь первого сотрудника</div>';document.querySelectorAll('.editStaff').forEach(b=>b.onclick=()=>openStaff(b.dataset.id))}
function renderAll(){renderMonth();renderDay();renderManage()}
function openMark(id,k){const a=db.staff.find(x=>x.id===id),x=mark(id,k);$('editId').value=id;$('editDate').value=k;$('editStatus').value=x.status;$('editNorm').value=x.norm||'';$('editNote').value=x.note||'';$('editTitle').textContent=a.name;$('editDialog').showModal()}
function openStaff(id=''){const a=db.staff.find(x=>x.id===id);$('staffId').value=id;$('staffName').value=a?.name||'';$('staffRole').value=a?.role||'Администратор';$('staffYellow').value=a?.yellow||0;$('staffRed').value=a?.red||0;$('staffTitle').textContent=a?'Изменить сотрудника':'Добавить сотрудника';$('deleteStaff').hidden=!a;$('staffDialog').showModal()}
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').textContent='';const {error}=await sb.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error)return $('authError').textContent=error.message;await session()});
$('registerBtn').addEventListener('click',async()=>{$('authError').textContent='';const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||password.length<6)return $('authError').textContent='Введите email и пароль минимум из 6 символов.';const {data,error}=await sb.auth.signUp({email,password});if(error)return $('authError').textContent=error.message;$('authError').textContent=data.session?'Регистрация успешна. Входим…':'Регистрация успешна. Если включено подтверждение почты — подтвердите email.';if(data.session)await session()});
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();await session()};$('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');
$('prevBtn').onclick=()=>{month.setMonth(month.getMonth()-1);renderMonth()};$('nextBtn').onclick=()=>{month.setMonth(month.getMonth()+1);renderMonth()};$('searchInput').oninput=renderMonth;$('roleSelect').onchange=renderMonth;$('dayDate').value=new Date().toLocaleDateString('en-CA');$('dayDate').onchange=renderDay;$('addBtn').onclick=()=>openStaff();
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));['month','day','manage'].forEach(v=>$(v+'View').hidden=v!==b.dataset.view);renderAll()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('editForm').onsubmit=async e=>{e.preventDefault();const id=$('editId').value,k=$('editDate').value,status=$('editStatus').value;let res=status==='none'?await sb.from('daily_marks').delete().eq('staff_id',id).eq('mark_date',k):await sb.from('daily_marks').upsert({staff_id:id,mark_date:k,status,norm_value:+$('editNorm').value||0,note:$('editNote').value.trim()},{onConflict:'staff_id,mark_date'});if(res.error)return alert(res.error.message);$('editDialog').close();await load()};
$('staffForm').onsubmit=async e=>{e.preventDefault();const id=$('staffId').value,data={name:$('staffName').value.trim(),role:$('staffRole').value,yellow_cards:+$('staffYellow').value||0,red_cards:+$('staffRed').value||0},res=id?await sb.from('staff').update(data).eq('id',id):await sb.from('staff').insert(data);if(res.error)return alert(res.error.message);$('staffDialog').close();await load()};$('deleteStaff').onclick=async()=>{if(confirm('Удалить сотрудника и все его отметки?')){const {error}=await sb.from('staff').delete().eq('id',$('staffId').value);if(error)return alert(error.message);$('staffDialog').close();await load()}};
await session();});