-- Выполни этот файл в Supabase SQL Editor
create table if not exists public.staff (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  role text not null default 'Администратор',
  yellow_cards int not null default 0 check (yellow_cards between 0 and 3),
  red_cards int not null default 0 check (red_cards between 0 and 1),
  appointed_at date not null default current_date,
  dismissed_at date,
  created_at timestamptz not null default now()
);
alter table public.staff add column if not exists appointed_at date not null default current_date;
alter table public.staff add column if not exists dismissed_at date;

create table if not exists public.daily_marks (
  id bigint generated by default as identity primary key,
  staff_id uuid not null references public.staff(id) on delete cascade,
  mark_date date not null,
  status text not null check (status in ('norm','inactive')),
  norm_value int not null default 0 check (norm_value >= 0),
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique(staff_id, mark_date)
);
alter table public.staff enable row level security;
alter table public.daily_marks enable row level security;
drop policy if exists "staff_public_read" on public.staff;
drop policy if exists "marks_public_read" on public.daily_marks;
drop policy if exists "staff_auth_write" on public.staff;
drop policy if exists "marks_auth_write" on public.daily_marks;
create policy "staff_public_read" on public.staff for select using (true);
create policy "marks_public_read" on public.daily_marks for select using (true);
create policy "staff_auth_write" on public.staff for all to authenticated using (true) with check (true);
create policy "marks_auth_write" on public.daily_marks for all to authenticated using (true) with check (true);
create index if not exists daily_marks_date_idx on public.daily_marks(mark_date);
create index if not exists daily_marks_staff_idx on public.daily_marks(staff_id);

create table if not exists public.schedule_assignments (
  id bigint generated by default as identity primary key,
  work_date date not null,
  slot_key text not null check (slot_key in ('06-08','08-11','11-13','13-16','16-19','19-21','21-00','00-02')),
  staff_id uuid not null references public.staff(id) on delete cascade,
  comment text not null default '',
  created_at timestamptz not null default now(),
  unique(work_date, slot_key, staff_id)
);
alter table public.schedule_assignments enable row level security;
drop policy if exists "schedule_public_read" on public.schedule_assignments;
drop policy if exists "schedule_auth_write" on public.schedule_assignments;
create policy "schedule_public_read" on public.schedule_assignments for select using (true);
create policy "schedule_auth_write" on public.schedule_assignments for all to authenticated using (true) with check (true);
create index if not exists schedule_assignments_date_idx on public.schedule_assignments(work_date);


create table if not exists public.schedule_slots (
  slot_key text primary key check (slot_key in ('06-08','08-11','11-13','13-16','16-19','19-21','21-00','00-02')),
  capacity int not null check (capacity between 1 and 20),
  updated_at timestamptz not null default now()
);
insert into public.schedule_slots(slot_key,capacity) values
('06-08',2),('08-11',2),('11-13',3),('13-16',3),('16-19',3),('19-21',3),('21-00',2),('00-02',2)
on conflict (slot_key) do nothing;
alter table public.schedule_slots enable row level security;
drop policy if exists "schedule_slots_public_read" on public.schedule_slots;
drop policy if exists "schedule_slots_auth_write" on public.schedule_slots;
create policy "schedule_slots_public_read" on public.schedule_slots for select using (true);
create policy "schedule_slots_auth_write" on public.schedule_slots for all to authenticated using (true) with check (true);
