-- Выполни этот файл в Supabase SQL Editor
create table if not exists public.staff (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  role text not null default 'Администратор',
  yellow_cards int not null default 0 check (yellow_cards between 0 and 3),
  red_cards int not null default 0 check (red_cards between 0 and 1),
  appointed_at date not null default current_date,
  dismissed_at date,
  created_at timestamptz not null default now()
);
alter table public.staff add column if not exists appointed_at date not null default current_date;
alter table public.staff add column if not exists dismissed_at date;

create table if not exists public.daily_marks (
  id bigint generated by default as identity primary key,
  staff_id uuid not null references public.staff(id) on delete cascade,
  mark_date date not null,
  status text not null check (status in ('norm','inactive')),
  norm_value int not null default 0 check (norm_value >= 0),
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique(staff_id, mark_date)
);
alter table public.staff enable row level security;
alter table public.daily_marks enable row level security;
drop policy if exists "staff_public_read" on public.staff;
drop policy if exists "marks_public_read" on public.daily_marks;
drop policy if exists "staff_auth_write" on public.staff;
drop policy if exists "marks_auth_write" on public.daily_marks;
create policy "staff_public_read" on public.staff for select using (true);
create policy "marks_public_read" on public.daily_marks for select using (true);
create policy "staff_auth_write" on public.staff for all to authenticated using (true) with check (true);
create policy "marks_auth_write" on public.daily_marks for all to authenticated using (true) with check (true);
create index if not exists daily_marks_date_idx on public.daily_marks(mark_date);
create index if not exists daily_marks_staff_idx on public.daily_marks(staff_id);