-- v52: profiles, avatars and administration chat
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  avatar_url text not null default '',
  bio text not null default '',
  updated_at timestamptz not null default now()
);
alter table public.user_profiles enable row level security;
drop policy if exists "profiles_auth_read" on public.user_profiles;
create policy "profiles_auth_read" on public.user_profiles for select to authenticated using (true);
drop policy if exists "profiles_self_insert" on public.user_profiles;
create policy "profiles_self_insert" on public.user_profiles for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "profiles_self_update" on public.user_profiles;
create policy "profiles_self_update" on public.user_profiles for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('avatars','avatars',true,3145728,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true,file_size_limit=3145728,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects for select using (bucket_id='avatars');
drop policy if exists "avatars_self_insert" on storage.objects;
create policy "avatars_self_insert" on storage.objects for insert to authenticated with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatars_self_update" on storage.objects;
create policy "avatars_self_update" on storage.objects for update to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatars_self_delete" on storage.objects;
create policy "avatars_self_delete" on storage.objects for delete to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1500),
  reply_to bigint references public.chat_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  edited_at timestamptz
);
create index if not exists chat_messages_created_idx on public.chat_messages(created_at desc);
alter table public.chat_messages enable row level security;
drop policy if exists "chat_auth_read" on public.chat_messages;
create policy "chat_auth_read" on public.chat_messages for select to authenticated using (public.current_app_role()<>'blocked');
drop policy if exists "chat_self_insert" on public.chat_messages;
create policy "chat_self_insert" on public.chat_messages for insert to authenticated with check (user_id=auth.uid() and public.current_app_role()<>'blocked');
drop policy if exists "chat_self_update" on public.chat_messages;
create policy "chat_self_update" on public.chat_messages for update to authenticated using (user_id=auth.uid() and public.current_app_role()<>'blocked') with check (user_id=auth.uid());
drop policy if exists "chat_self_delete" on public.chat_messages;
create policy "chat_self_delete" on public.chat_messages for delete to authenticated using (user_id=auth.uid() or public.current_app_role() in ('creator','chief_admin'));

create table if not exists public.chat_reactions (
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍','❤️','😂','🔥','👏')),
  created_at timestamptz not null default now(),
  primary key(message_id,user_id,emoji)
);
alter table public.chat_reactions enable row level security;
drop policy if exists "reactions_auth_read" on public.chat_reactions;
create policy "reactions_auth_read" on public.chat_reactions for select to authenticated using (public.current_app_role()<>'blocked');
drop policy if exists "reactions_self_insert" on public.chat_reactions;
create policy "reactions_self_insert" on public.chat_reactions for insert to authenticated with check (user_id=auth.uid() and public.current_app_role()<>'blocked');
drop policy if exists "reactions_self_delete" on public.chat_reactions;
create policy "reactions_self_delete" on public.chat_reactions for delete to authenticated using (user_id=auth.uid());

alter table public.chat_messages replica identity full;
alter table public.chat_reactions replica identity full;
do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.chat_reactions;
exception when duplicate_object then null; end $$;
