-- v53: lock same-day self schedule changes and add replacement workflow
create table if not exists public.schedule_replacements (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.schedule_assignments(id) on delete cascade,
  requester_user_id uuid not null references auth.users(id) on delete cascade,
  original_staff_id uuid not null references public.staff(id) on delete cascade,
  replacement_staff_id uuid not null references public.staff(id) on delete restrict,
  reason text not null default '',
  status text not null default 'pending' check (status in ('pending','accepted','rejected','cancelled')),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  unique(assignment_id) deferrable initially immediate
);
alter table public.schedule_replacements enable row level security;
drop policy if exists "replacement_auth_read" on public.schedule_replacements;
create policy "replacement_auth_read" on public.schedule_replacements for select to authenticated using (public.current_app_role()<>'blocked');

-- remove the old direct self-delete permission; creator/GA management policy remains
drop policy if exists "schedule_self_delete" on public.schedule_assignments;
drop policy if exists "schedule_assignments_self_delete" on public.schedule_assignments;
drop policy if exists "admin_trainee_self_delete" on public.schedule_assignments;

create or replace function public.remove_my_future_shift(p_assignment bigint)
returns void language plpgsql security definer set search_path=public as $$
declare v_a public.schedule_assignments%rowtype; v_staff uuid;
begin
  if public.current_app_role() not in ('admin','trainee') then raise exception 'Недостаточно прав'; end if;
  select staff_id into v_staff from public.user_roles where user_id=auth.uid();
  select * into v_a from public.schedule_assignments where id=p_assignment for update;
  if v_a.id is null or v_a.staff_id is distinct from v_staff then raise exception 'Смена не найдена'; end if;
  if v_a.work_date <= current_date then raise exception 'В день смены менять график уже нельзя. Используйте «Нужна замена».'; end if;
  delete from public.schedule_assignments where id=p_assignment;
end $$;
grant execute on function public.remove_my_future_shift(bigint) to authenticated;

create or replace function public.request_schedule_replacement(p_assignment bigint,p_replacement_staff uuid,p_reason text default '')
returns bigint language plpgsql security definer set search_path=public as $$
declare v_a public.schedule_assignments%rowtype; v_staff uuid; v_id bigint;
begin
  if public.current_app_role() not in ('admin','trainee') then raise exception 'Недостаточно прав'; end if;
  select staff_id into v_staff from public.user_roles where user_id=auth.uid();
  select * into v_a from public.schedule_assignments where id=p_assignment for update;
  if v_a.id is null or v_a.staff_id is distinct from v_staff then raise exception 'Это не ваша смена'; end if;
  if v_a.work_date <> current_date then raise exception 'Запрос замены доступен в день смены'; end if;
  if p_replacement_staff=v_staff then raise exception 'Нельзя указать самого себя как замену'; end if;
  if not exists(select 1 from public.staff where id=p_replacement_staff and dismissed_at is null) then raise exception 'Сотрудник для замены не найден'; end if;
  if exists(select 1 from public.schedule_replacements where assignment_id=p_assignment and status='pending') then raise exception 'По этой смене уже запрошена замена'; end if;
  insert into public.schedule_replacements(assignment_id,requester_user_id,original_staff_id,replacement_staff_id,reason)
  values(p_assignment,auth.uid(),v_staff,p_replacement_staff,left(trim(coalesce(p_reason,'')),300))
  returning id into v_id;
  return v_id;
end $$;
grant execute on function public.request_schedule_replacement(bigint,uuid,text) to authenticated;

create or replace function public.decide_schedule_replacement(p_replacement bigint,p_accept boolean)
returns void language plpgsql security definer set search_path=public as $$
declare v_r public.schedule_replacements%rowtype; v_staff uuid; v_a public.schedule_assignments%rowtype; v_count int;
begin
  select * into v_r from public.schedule_replacements where id=p_replacement for update;
  if v_r.id is null or v_r.status<>'pending' then raise exception 'Запрос замены уже закрыт или не найден'; end if;
  select staff_id into v_staff from public.user_roles where user_id=auth.uid();
  if public.current_app_role() not in ('creator','chief_admin') and v_staff is distinct from v_r.replacement_staff_id then
    raise exception 'Подтвердить замену может только указанный сотрудник или руководство';
  end if;
  if not p_accept then
    update public.schedule_replacements set status='rejected',decided_at=now() where id=p_replacement;
    return;
  end if;
  select * into v_a from public.schedule_assignments where id=v_r.assignment_id for update;
  if v_a.id is null then raise exception 'Исходная смена не найдена'; end if;
  select count(*) into v_count from public.schedule_assignments where work_date=v_a.work_date and staff_id=v_r.replacement_staff_id and id<>v_a.id;
  if v_count>=2 then raise exception 'У заменяющего уже максимум 2 смены в этот день'; end if;
  if exists(select 1 from public.schedule_assignments where work_date=v_a.work_date and slot_key=v_a.slot_key and staff_id=v_r.replacement_staff_id and id<>v_a.id) then
    raise exception 'Этот сотрудник уже находится в данной смене';
  end if;
  update public.schedule_assignments set staff_id=v_r.replacement_staff_id where id=v_a.id;
  update public.schedule_replacements set status='accepted',decided_at=now() where id=p_replacement;
end $$;
grant execute on function public.decide_schedule_replacement(bigint,boolean) to authenticated;
