-- v64: private conversations, participants, unread/read state
create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'direct' check (kind in ('direct')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_conversation_members (
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  reply_to bigint references public.private_messages(id) on delete set null,
  attachment_url text not null default '',
  attachment_name text not null default '',
  attachment_type text not null default '',
  attachment_size bigint not null default 0,
  edited_at timestamptz,
  created_at timestamptz not null default now(),
  constraint private_messages_content_check check (
    char_length(trim(body)) between 1 and 1500
    or (char_length(trim(body))=0 and char_length(trim(attachment_url))>0)
  )
);

create index if not exists private_messages_conversation_created_idx
on public.private_messages(conversation_id,created_at);

alter table public.chat_conversations enable row level security;
alter table public.chat_conversation_members enable row level security;
alter table public.private_messages enable row level security;

drop policy if exists "conversation_member_read" on public.chat_conversations;
create policy "conversation_member_read" on public.chat_conversations for select to authenticated
using (exists(select 1 from public.chat_conversation_members m where m.conversation_id=id and m.user_id=auth.uid()));

drop policy if exists "members_member_read" on public.chat_conversation_members;
create policy "members_member_read" on public.chat_conversation_members for select to authenticated
using (exists(select 1 from public.chat_conversation_members me where me.conversation_id=conversation_id and me.user_id=auth.uid()));

drop policy if exists "members_self_update" on public.chat_conversation_members;
create policy "members_self_update" on public.chat_conversation_members for update to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "private_member_read" on public.private_messages;
create policy "private_member_read" on public.private_messages for select to authenticated
using (exists(select 1 from public.chat_conversation_members m where m.conversation_id=private_messages.conversation_id and m.user_id=auth.uid()));

drop policy if exists "private_member_insert" on public.private_messages;
create policy "private_member_insert" on public.private_messages for insert to authenticated
with check (user_id=auth.uid() and exists(select 1 from public.chat_conversation_members m where m.conversation_id=private_messages.conversation_id and m.user_id=auth.uid()));

drop policy if exists "private_own_update" on public.private_messages;
create policy "private_own_update" on public.private_messages for update to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "private_own_delete" on public.private_messages;
create policy "private_own_delete" on public.private_messages for delete to authenticated
using(user_id=auth.uid() or public.current_app_role() in ('creator','chief_admin'));

create or replace function public.start_direct_conversation(p_other uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
 if auth.uid() is null then raise exception 'Необходимо войти'; end if;
 if p_other=auth.uid() then raise exception 'Нельзя создать диалог с собой'; end if;
 if not exists(select 1 from public.user_roles where user_id=p_other and coalesce(is_blocked,false)=false)
 then raise exception 'Пользователь недоступен'; end if;
 select c.id into v_id
 from public.chat_conversations c
 join public.chat_conversation_members a on a.conversation_id=c.id and a.user_id=auth.uid()
 join public.chat_conversation_members b on b.conversation_id=c.id and b.user_id=p_other
 where c.kind='direct'
 and (select count(*) from public.chat_conversation_members z where z.conversation_id=c.id)=2
 limit 1;
 if v_id is null then
   insert into public.chat_conversations(created_by) values(auth.uid()) returning id into v_id;
   insert into public.chat_conversation_members(conversation_id,user_id) values(v_id,auth.uid()),(v_id,p_other);
 end if;
 return v_id;
end $$;
grant execute on function public.start_direct_conversation(uuid) to authenticated;

create or replace function public.mark_private_conversation_read(p_conversation uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
 update public.chat_conversation_members set last_read_at=now()
 where conversation_id=p_conversation and user_id=auth.uid();
 if not found then raise exception 'Диалог не найден'; end if;
end $$;
grant execute on function public.mark_private_conversation_read(uuid) to authenticated;

create or replace function public.edit_my_private_message(p_message bigint,p_body text)
returns void language plpgsql security definer set search_path=public as $$
begin
 if char_length(trim(coalesce(p_body,''))) not between 1 and 1500 then raise exception 'Некорректная длина сообщения'; end if;
 update public.private_messages set body=trim(p_body),edited_at=now()
 where id=p_message and user_id=auth.uid();
 if not found then raise exception 'Сообщение не найдено'; end if;
end $$;
grant execute on function public.edit_my_private_message(bigint,text) to authenticated;
