-- v83: Telegram-like messenger foundation

create table if not exists public.chat_attachments (
  id bigint generated by default as identity primary key,
  public_message_id bigint references public.chat_messages(id) on delete cascade,
  private_message_id bigint references public.private_messages(id) on delete cascade,
  storage_path text not null default '',
  file_url text not null,
  file_name text not null default 'Файл',
  file_type text not null default '',
  file_size bigint not null default 0 check (file_size >= 0 and file_size <= 20971520),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint chat_attachment_one_parent check (
    (public_message_id is not null and private_message_id is null)
    or
    (public_message_id is null and private_message_id is not null)
  )
);

create index if not exists chat_attachments_public_idx on public.chat_attachments(public_message_id, sort_order);
create index if not exists chat_attachments_private_idx on public.chat_attachments(private_message_id, sort_order);

alter table public.chat_attachments enable row level security;

drop policy if exists "attachments_authenticated_read" on public.chat_attachments;
create policy "attachments_authenticated_read"
on public.chat_attachments for select to authenticated
using (
  (public_message_id is not null)
  or
  (private_message_id is not null and exists (
    select 1 from public.private_messages pm
    where pm.id = private_message_id
      and public.is_conversation_member(pm.conversation_id, auth.uid())
  ))
);

drop policy if exists "attachments_own_insert" on public.chat_attachments;
create policy "attachments_own_insert"
on public.chat_attachments for insert to authenticated
with check (
  (public_message_id is not null and exists (
    select 1 from public.chat_messages cm
    where cm.id = public_message_id and cm.user_id = auth.uid()
  ))
  or
  (private_message_id is not null and exists (
    select 1 from public.private_messages pm
    where pm.id = private_message_id
      and pm.user_id = auth.uid()
      and public.is_conversation_member(pm.conversation_id, auth.uid())
  ))
);

drop policy if exists "attachments_own_delete" on public.chat_attachments;
create policy "attachments_own_delete"
on public.chat_attachments for delete to authenticated
using (
  (public_message_id is not null and exists (
    select 1 from public.chat_messages cm where cm.id = public_message_id and cm.user_id = auth.uid()
  ))
  or
  (private_message_id is not null and exists (
    select 1 from public.private_messages pm where pm.id = private_message_id and pm.user_id = auth.uid()
  ))
);

create table if not exists public.chat_pins (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.chat_conversations(id) on delete cascade,
  public_message_id bigint references public.chat_messages(id) on delete cascade,
  private_message_id bigint references public.private_messages(id) on delete cascade,
  pinned_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint chat_pin_one_parent check (
    (conversation_id is null and public_message_id is not null and private_message_id is null)
    or
    (conversation_id is not null and public_message_id is null and private_message_id is not null)
  )
);

create unique index if not exists chat_pins_public_unique
on public.chat_pins(public_message_id) where public_message_id is not null;
create unique index if not exists chat_pins_private_unique
on public.chat_pins(conversation_id, private_message_id)
where private_message_id is not null;

alter table public.chat_pins enable row level security;

drop policy if exists "pins_authenticated_read" on public.chat_pins;
create policy "pins_authenticated_read"
on public.chat_pins for select to authenticated
using (
  conversation_id is null
  or public.is_conversation_member(conversation_id, auth.uid())
);

drop policy if exists "pins_authenticated_insert" on public.chat_pins;
create policy "pins_authenticated_insert"
on public.chat_pins for insert to authenticated
with check (
  pinned_by = auth.uid()
  and (
    conversation_id is null
    or public.is_conversation_member(conversation_id, auth.uid())
  )
);

drop policy if exists "pins_authenticated_delete" on public.chat_pins;
create policy "pins_authenticated_delete"
on public.chat_pins for delete to authenticated
using (
  pinned_by = auth.uid()
  or public.current_app_role() in ('creator','chief_admin')
);

alter table public.private_messages
  add column if not exists forwarded_from_user uuid references auth.users(id) on delete set null,
  add column if not exists forwarded_from_message bigint references public.private_messages(id) on delete set null;

alter table public.chat_messages
  add column if not exists forwarded_from_user uuid references auth.users(id) on delete set null;

do $$
begin
  begin alter publication supabase_realtime add table public.chat_attachments;
  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.chat_pins;
  exception when duplicate_object then null; end;
end $$;
